version: '3'
services:
  postgres:
    image: 'postgres:9.6.2-alpine'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=en_US.UTF-8'
      TZ: 'UTC'
    ports:
     - "5432:5432"
